MovieRec/MovieRec/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static # NOT for production
from movies import views


urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('register/', views.register, name='register'),
    path('movies/', include('movies.urls')),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

MovieRec/movies/urls.py
from django.urls import path
from movies import views

app_name = 'movies'

urlpatterns = [
    path('', views.movies, name='recommendations')
]

MovieRec/movies/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to="profile_pics", blank=True, null=True)

    def __str__(self):
        return(self.user.username)

class Movie(models.Model):
    title = models.CharField(max_length=50)
    
    DRAMA = 'DR'; COMEDY = 'CO'; HORROR = 'HO'; ACTION = 'AC'; ROMANCE = 'RO';
    GENRE_CHOICES = [(DRAMA, 'Drama'), (COMEDY, 'Comedy'), (HORROR, 'Horror'), (ACTION, 'Action'),(ROMANCE, 'Romance')]
    genre = models.CharField(max_length=2, choices=GENRE_CHOICES, blank=True, null=True)

    def __str__(self):
        return(self.title)

    def get_average_rating(self):
        default_rating = 3.0
        rate_total = 0.0
        num_rate = 0.0
        for rating in self.rating_set.all():
            rate_total += rating.value
            num_rate +=1
        if(num_rate>0):
            return(rate_total/num_rate)
        else:
            return(default_rating)


class Rating(models.Model):
    value = models.IntegerField(default=3, validators=[MaxValueValidator(5), MinValueValidator(1)])
    rater = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return(f"Rating: {self.rater} x {self.movie}")

MovieRec/movies/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Rating


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password', 'first_name')


class ProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('picture',)

class RatingForm(forms.ModelForm):
    class Meta():
        model = Rating
        fields = ('value', 'movie')

MovieRec/movies/views.py
from django.shortcuts import render
from .models import UserProfile, Movie, Rating
from .forms import UserForm, ProfileForm, RatingForm

from django.views.generic import ListView

#login stuff
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.

class Index(ListView):
    template_name = 'movies/index.html'
    queryset = sorted(Movie.objects.all(), key=lambda m: m.get_average_rating(), reverse=True)[:5]
    context_object_name = 'top_movies'

@login_required
def movies(request):
    return(render(request, 'movies/movie_page.html', context={'registered':False}))


def register(request):
    registered = False
    

    if(request.method == 'POST'):
        # new user has been registered
        userform = UserForm(data=request.POST)
        profileform = ProfileForm(data=request.POST)

        if(userform.is_valid() and profileform.is_valid()):
            #https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/#a-full-example
            
            user = userform.save() #.save() creates and saves a model object, 
            user.set_password(user.password)
            user.save()

            profile = profileform.save(commit=False)
            profile.user = user # form only has extra fields, match everything with userform data

            if('picture' in request.FILES):
                profile.picture = request.FILES['picture']
            
            profile.save()

            registered=True
        else:
            print("FORM ERROR")
    else:
        userform = UserForm()
        profileform = ProfileForm()

    c = {
        'userform': UserForm,
        'profileform' : ProfileForm,
        'registered' : registered,
    }

    return(render(request, 'movies/registration.html', context=c))



def user_login(request):
    
    if(request.method == 'POST'):
        username = request.POST.get('username') # standard HTML form, have to use get() for data
        password = request.POST.get('password')
        user = authenticate(username=username, password=password) #heavy lifting of whether real user

        if(user and user.is_active):
                login(request, user)
                return(HttpResponseRedirect(reverse('home')))
        else:
            return(HttpResponse("FAILED LOGIN"))

    c = {}
    return(render(request, 'movies/login.html', context=c))

@login_required
def user_logout(request):
    logout(request)
    return(HttpResponseRedirect(reverse('home')))

MovieRec/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Recommendations</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          <li> <a class="navbar-brand" href="{% url 'home' %}">Home</a> </li>
          <li> <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="nav-item nav-link" href="{% url 'register' %}">Register</a> </li>
          <li> <a class="nav-item nav-link" href="{% url 'movies:recommendations' %}"> My List</a></li>

          {# login navigation #}

          {% if user.is_authenticated %}
            
            <li> <a class="nav-link" href="{% url 'logout' %}"> Logout</a></li>
          {% else %}
            <li><a class="nav-link" href="{% url 'login' %}"> Login</a></li>
          {%endif%}

        </ul>
      </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

MovieRec/templates/movies/index.html
{% extends 'movies/base.html' %}
{% load static %}

{%block content %}

<div class="jumbotron">
    <h1>Welcome to MovieRex! </h1>

    <p>Top 5 highest rated movies to check out:</p>
    <ul>
        {% for movie in top_movies %}
        <li> {{movie.title}} </li>
        {%endfor%}
    </ul>
</div>


{% endblock %}

MovieRec/templates/movies/login.html
{% extends 'movies/base.html' %}
{% load static %}

{%block content %}

    <div class="jumbotron">
        <h1>Please Login!</h1>

        <form action="{% url 'login' %}" method='POST'>
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password"> Password: </label>
            <input type="password" name="password">

            <input type="submit" name="" value="Login">

        </form>

    </div>
    
{% endblock %}

MovieRec/templates/movies/movie_page.html
{% extends 'movies/base.html' %}
{% load static %}

{% block content %}

    <h1>Movie Recommendations for You</h1>

    {% if user.is_authenticated %}

        <ul>
            <li>
                M1
            </li>
        </ul>
    {% else %}

    <div class="jumbotron">
        <h1>Please Login!</h1>
    </div>

    {%endif%}

{% endblock %}

MovieRec/templates/movies/registration.html
{% extends 'movies/base.html' %}
{% load static %}

{%block content %}
<div class="jumbotron">

    {% if registered %}

        <h1>Thank you, you have registered!</h1>

    {% else %}

    <h1> Register for Movie Recommendations! </h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ userform.as_p }}
        {{ profileform.as_p }}

        <input type="submit" value="Register">
    
    </form>

    {% endif %}
</div>
{% endblock %}